FROM node:16-alpine3.15 as builder

# copy files
WORKDIR /multilayer_perceptron
COPY . .

# remove local node modules
RUN rm -rf /app/node_modules

# install dependencies
RUN npm install

# compile
RUN npm run build

FROM nginx:stable-alpine3.17-slim

# copy builded files
WORKDIR /multilayer_perceptron
COPY --from=builder /multilayer_perceptron/build /usr/share/nginx/html
